#ifndef JACKPOT_CONST_H
#define JACKPOT_CONST_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 600
#define NB_ROLLS 3
#define X_ROLL1 364
#define X_ROLL2 516
#define X_ROLL3 673

#endif //JACKPOT_CONST_H
